services:
  backend:
    build: ./backend
    container_name: codebyme_backend
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-codebyme}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-566235}
    ports:
      - "127.0.0.1:8083:8080"
    depends_on:
      - db
    networks:
      - codebyme_net

  frontend:
    build: ./frontend
    container_name: codebyme_frontend
    restart: unless-stopped
    environment:
      # This tells SvelteKit's Node adapter where the backend is (Docker DNS name)
      - ORIGIN=https://codebyme.de
    ports:
      - "127.0.0.1:8082:3000" # Host Port 8082 -> Container Port 3000
    depends_on:
      - backend
    networks:
      - codebyme_net

  db:
    image: postgres:16-alpine
    container_name: codebyme_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-codebyme}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-566235}
    volumes:
      - codebyme_db_data:/var/lib/postgresql/data
    networks:
      - codebyme_net

networks:
  codebyme_net:
    driver: bridge

volumes:
  codebyme_db_data:
